"""
Ausgabe-Formatierer für Scan-Ergebnisse.

Wandelt ReconResult-Objekte in JSON- oder Markdown-Berichte um.
Wird vom Orchestrator und der MCP-API genutzt, um Ergebnisse
für unterschiedliche Konsumenten aufzubereiten.
"""

import json
from dataclasses import asdict
from datetime import datetime
from typing import Any

from src.agents.recon.result_types import ReconResult, VulnerabilityFinding
from src.shared.constants.severity import SEVERITY_ICONS, SEVERITY_ORDER

# Lokale Aliase — bestehende Referenzen nutzen Underscore-Prefix
_SEVERITY_ICONS = SEVERITY_ICONS
_SEVERITY_ORDER = SEVERITY_ORDER


def format_as_json(result: ReconResult) -> str:
    """Wandelt ein ReconResult in formatiertes JSON um.

    Nutzt dataclasses.asdict für die Serialisierung und gibt
    eingerücktes JSON mit sortierten Schlüsseln zurück.

    Args:
        result: Das Scan-Ergebnis als ReconResult-Objekt

    Returns:
        Pretty-printed JSON-String
    """
    data: dict[str, Any] = asdict(result)
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=False)


def format_as_markdown(result: ReconResult) -> str:
    """Erstellt einen Markdown-Bericht aus einem ReconResult.

    Erzeugt einen vollständigen Bericht mit Zusammenfassung,
    Port-Tabelle, Schwachstellen-Liste und Agent-Übersicht.

    Args:
        result: Das Scan-Ergebnis als ReconResult-Objekt

    Returns:
        Vollständiger Markdown-Bericht als String
    """
    # Berichts-Zeitstempel
    report_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines: list[str] = []

    # --- Kopfzeile ---
    lines.append(f"# SentinelClaw Scan Report: {result.target}")
    lines.append("")
    lines.append(f"**Report generated:** {report_time}")
    lines.append("")

    # --- Zusammenfassung ---
    lines.append("## Summary")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| Hosts discovered | {result.total_hosts} |")
    lines.append(f"| Open ports | {result.total_open_ports} |")
    lines.append(f"| Vulnerabilities | {result.total_vulnerabilities} |")
    lines.append(f"| Scan duration | {result.scan_duration_seconds:.1f}s |")
    lines.append(f"| Tokens used | {result.total_tokens_used:,} |")
    lines.append(f"| Phases completed | {result.phases_completed} |")
    lines.append("")

    # Schweregrad-Verteilung (nur wenn Schwachstellen vorhanden)
    severity_counts = result.severity_counts
    if severity_counts:
        lines.append("### Severity Distribution")
        lines.append("")
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = severity_counts.get(sev, 0)
            if count > 0:
                icon = _SEVERITY_ICONS.get(sev, "")
                lines.append(f"- {icon} **{sev.capitalize()}:** {count}")
        lines.append("")

    # --- Offene Ports ---
    if result.open_ports:
        lines.append("## Open Ports")
        lines.append("")
        lines.append("| Host | Port | Service | Version |")
        lines.append("|------|------|---------|---------|")
        for port in result.open_ports:
            service = port.service or "-"
            version = port.version or "-"
            lines.append(
                f"| {port.host} | {port.port}/{port.protocol} "
                f"| {service} | {version} |"
            )
        lines.append("")

    # --- Schwachstellen ---
    if result.vulnerabilities:
        lines.append("## Vulnerabilities")
        lines.append("")

        # Nach Schweregrad sortieren (kritisch zuerst)
        sorted_vulns = sorted(
            result.vulnerabilities,
            key=lambda v: _SEVERITY_ORDER.get(v.severity.lower(), 99),
        )

        for vuln in sorted_vulns:
            _append_vulnerability(lines, vuln)

    # --- Risikobewertung ---
    if result.risk_assessment:
        lines.append("## Risk Assessment")
        lines.append("")
        lines.append(result.risk_assessment)
        lines.append("")

    # --- Agent-Zusammenfassung ---
    if result.agent_summary:
        lines.append("## Agent Summary")
        lines.append("")
        lines.append(result.agent_summary)
        lines.append("")

    # --- Fehler (nur wenn vorhanden) ---
    if result.errors:
        lines.append("## Errors")
        lines.append("")
        for error in result.errors:
            lines.append(f"- {error}")
        lines.append("")

    # Abschlusszeile
    lines.append("---")
    lines.append(f"*Generated by SentinelClaw v0.1 (PoC) at {report_time}*")
    lines.append("")

    return "\n".join(lines)


def _append_vulnerability(lines: list[str], vuln: VulnerabilityFinding) -> None:
    """Fügt eine einzelne Schwachstelle zum Markdown-Bericht hinzu.

    Hilfsfunktion für format_as_markdown — hält die Hauptfunktion
    übersichtlich.

    Args:
        lines: Die bisherigen Berichtszeilen (wird in-place erweitert)
        vuln: Der Schwachstellen-Fund
    """
    sev_lower = vuln.severity.lower()
    icon = _SEVERITY_ICONS.get(sev_lower, "")
    cve_tag = f" ({vuln.cve_id})" if vuln.cve_id else ""

    lines.append(f"### {icon} {vuln.title}{cve_tag}")
    lines.append("")
    lines.append(f"- **Severity:** {vuln.severity.capitalize()}")

    if vuln.cvss_score > 0:
        lines.append(f"- **CVSS:** {vuln.cvss_score}")
    if vuln.host:
        location = vuln.host
        if vuln.port is not None:
            location += f":{vuln.port}"
        lines.append(f"- **Location:** {location}")
    if vuln.description:
        lines.append(f"- **Description:** {vuln.description}")
    if vuln.recommendation:
        lines.append(f"- **Recommendation:** {vuln.recommendation}")

    lines.append("")
